# Builder stage
FROM node:14-alpine AS builder

# Use /app as the CWD
WORKDIR /app

# Copy package.json and package-lock.json to working directory
COPY package.json ./

RUN npm install

# Copy the rest of the source code
COPY . .

RUN npm run build


# Final stage
FROM nginx:stable-alpine

# Copy build files from stage 1 'builder' to stage 2 'final'
COPY --from=builder /app/build /usr/share/nginx/html

# EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]    